#!/usr/bin/env python3
# Copyright (c) 2026 The Bitcoin Core developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.
"""Verify/generate forwarding wrappers using an explicitly reviewed method policy.

Run with --write after reviewing interface changes and updating thread_policy.json.
The parser deliberately only supports the declarations in the pinned interfaces;
an unsupported declaration is an error, never an uninstrumented fallback.
"""

import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent


def body(source, name):
    start = re.search(r"class " + name + r"(?:\s*:\s*public \w+)?\s*\{", source).end()
    depth = 1
    for pos in range(start, len(source)):
        depth += (source[pos] == "{") - (source[pos] == "}")
        if depth == 0:
            return source[start:pos]
    raise ValueError(f"Unclosed class: {name}")


def split_params(params):
    result = []
    depth = 0
    start = 0
    for pos, char in enumerate(params + ","):
        depth += (char in "<{(") - (char in ">})")
        if char == "," and depth == 0:
            value = params[start:pos].split("=", 1)[0].strip()
            if value:
                result.append(value)
            start = pos + 1
    return result


def declarations(name):
    header = "wallet" if name in ("Wallet", "WalletLoader") else "chain" if name in ("Chain", "ChainClient") else "node"
    source = (ROOT / f"bitcoin/src/interfaces/{header}.h").read_text(encoding="utf8")
    source = re.sub(r"//[^\n]*|/\*.*?\*/", "", source, flags=re.S)
    source = body(source, name)
    if name == "Chain":
        nested = body(source, "Notifications")
        source = source.replace(nested, "")
    matches = list(re.finditer(r"virtual\s+([^;{}]+?\([^;{}]*(?:\{\}[^;{}]*)*\))\s*(?:=\s*0\s*;|\{[^{}]*\})", source))
    # Destructors have no backend operation. Every other virtual must be parsed.
    count = len(re.findall(r"\bvirtual\b", source)) - len(re.findall(r"virtual\s+~", source))
    matches = [m for m in matches if not m[1].startswith("~")]
    if len(matches) != count:
        raise ValueError(f"Unsupported virtual declaration in {name}: parsed {len(matches)}/{count}")
    methods = []
    for match in matches:
        signature = " ".join(match[1].split())
        ret, method, params = re.fullmatch(r"(.+?)\s+(\w+)\((.*)\)", signature).groups()
        params = split_params(params)
        signature = f"{ret} {method}({', '.join(params)})"
        args = []
        for param in params:
            arg = re.search(r"(\w+)$", param)[1]
            args.append(arg if "&" in param and "&&" not in param else f"std::move({arg})")
        methods.append((method, signature, ", ".join(args)))
    if name == "WalletLoader":
        methods = declarations("ChainClient") + methods
    return methods


def generate(policies):
    lines = ["// Generated by test/generate_thread_audit.py --write. Do not edit.",
             "// Each policy is reviewed in test/thread_policy.json.", "using namespace interfaces;", ""]
    seen = set()
    for name in ("Wallet", "WalletLoader", "Chain", "Node"):
        lines += [f"class Checked{name} final : public {name}", "{", "public:",
                  f"    Checked{name}(std::unique_ptr<{name}> backend, std::shared_ptr<ThreadAudit> audit)",
                  "        : m_owner{std::move(backend)}, m_backend{m_owner.get()}, m_audit{std::move(audit)} {}"]
        if name == "WalletLoader":
            lines += ["    CheckedWalletLoader(WalletLoader& backend, std::shared_ptr<ThreadAudit> audit)",
                      "        : m_backend{&backend}, m_audit{std::move(audit)} {}"]
        for method, signature, args in declarations(name):
            key = f"{name}::{method}"
            seen.add(key)
            policy = policies[key]
            if not policy["reason"] or policy["policy"] not in {"Worker", "Bootstrap", "LocalShutdown", "LocalAccessor", "Forbidden"}:
                raise ValueError(f"Missing or invalid policy for {key}")
            if policy["signature"] != signature:
                raise ValueError(f"Review changed declaration for {key}: {signature}")
            check = f'        m_audit->check("{key}", ThreadPolicy::{policy["policy"]});'
            call = f"m_backend->{method}({args})"
            code = [f"        return {call};"]
            if key == "Node::walletLoader":
                code = ["        std::lock_guard lock{m_loader_mutex};",
                        "        if (!m_loader) m_loader = std::make_unique<CheckedWalletLoader>(m_backend->walletLoader(), m_audit);",
                        "        return *m_loader;"]
            elif name == "WalletLoader" and method in ("createWallet", "loadWallet", "restoreWallet"):
                code = [f"        auto result = {call};", "        if (result) *result = CheckWallet(std::move(*result), m_audit);", "        return result;"]
            elif key == "WalletLoader::migrateWallet":
                code = [f"        auto result = {call};", "        if (result) result->wallet = CheckWallet(std::move(result->wallet), m_audit);", "        return result;"]
            elif key == "WalletLoader::getWallets":
                code = [f"        auto wallets = {call};", "        for (auto& wallet : wallets) wallet = CheckWallet(std::move(wallet), m_audit);", "        return wallets;"]
            elif key == "WalletLoader::handleLoadWallet":
                code = ["        return m_backend->handleLoadWallet([audit = m_audit, fn = std::move(fn)](std::unique_ptr<Wallet> wallet) {",
                        "            fn(CheckWallet(std::move(wallet), audit));", "        });"]
            elif key == "Node::listExternalSigners":
                # A signer only exposes its display name. Keep even that call
                # audited; future interface additions are checked below too.
                code = [f"        auto signers = {call};",
                        "        for (auto& signer : signers) signer = std::make_unique<CheckedExternalSigner>(std::move(signer), m_audit);",
                        "        return signers;"]
            lines += [f"    {signature} override", "    {", check, *code, "    }"]
        lines += ["private:", f"    std::unique_ptr<{name}> m_owner;", f"    {name}* m_backend;", "    std::shared_ptr<ThreadAudit> m_audit;"]
        if name == "Node":
            lines += ["    std::mutex m_loader_mutex;", "    std::unique_ptr<CheckedWalletLoader> m_loader;"]
        lines += ["};", ""]
    # Keep the small signer wrapper before Node's factory forwarding method.
    signer_method, signer_signature, _ = declarations("ExternalSigner")[0]
    key = f"ExternalSigner::{signer_method}"
    if len(declarations("ExternalSigner")) != 1 or policies[key]["signature"] != signer_signature:
        raise ValueError("Review ExternalSigner changes")
    seen.add(key)
    lines[4:4] = ["class CheckedExternalSigner final : public ExternalSigner {", "public:",
                  "    CheckedExternalSigner(std::unique_ptr<ExternalSigner> backend, std::shared_ptr<ThreadAudit> audit)",
                  "        : m_backend{std::move(backend)}, m_audit{std::move(audit)} {}",
                  f'    {signer_signature} override {{ m_audit->check("{key}", ThreadPolicy::{policies[key]["policy"]}); return m_backend->getName(); }}',
                  "private:", "    std::unique_ptr<ExternalSigner> m_backend;", "    std::shared_ptr<ThreadAudit> m_audit;", "};", ""]
    if seen != policies.keys():
        raise ValueError(f"Stale policy entries: {policies.keys() - seen}")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    policies = json.loads((ROOT / "test/thread_policy.json").read_text(encoding="utf8"))
    generated = generate(policies)
    target = ROOT / "test/thread_audit_generated.inc"
    if args.write:
        target.write_text(generated, encoding="utf8")
    elif target.read_text(encoding="utf8") != generated:
        raise SystemExit("Thread wrappers out of date. Review policy and run test/generate_thread_audit.py --write")


if __name__ == "__main__":
    main()
